/**
 * Generate TypeScript types from backend Pydantic models.
 *
 * Pipeline: Python (model_json_schema) → JSON Schema → TypeScript
 *
 * Uses a custom converter instead of json-schema-to-typescript because
 * Pydantic v2 schemas include per-property `title` fields and duplicated
 * `$defs` that produce broken output with generic converters.
 *
 * Usage:
 *   node scripts/generate-types.mjs
 *   pnpm run generate:types
 */

import { execSync } from "node:child_process";
import { writeFileSync, mkdirSync, existsSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const BACKEND_DIR = resolve(__dirname, "../../CHATVOTE-BackEnd");
const OUTPUT_DIR = resolve(__dirname, "../src/lib/generated");
const OUTPUT_FILE = resolve(OUTPUT_DIR, "backend-types.generated.ts");

// ── Step 1: Get JSON Schemas from Python ──────────────────────────────

console.log("[generate-types] Running Python schema exporter...");
let raw;
try {
  raw = execSync("poetry run python scripts/generate_ts_types.py", {
    cwd: BACKEND_DIR,
    encoding: "utf-8",
    shell: "/bin/bash",
    timeout: 30_000,
  });
} catch (err) {
  if (existsSync(OUTPUT_FILE)) {
    console.warn(
      "[generate-types] Python exporter unavailable, using existing generated file.",
    );
    process.exit(0);
  }
  console.error("[generate-types] Failed to run Python exporter:", err.message);
  console.error(
    "[generate-types] No existing generated file found. Install poetry and backend dependencies first.",
  );
  process.exit(1);
}

const { schemas, socket_events, name_map } = JSON.parse(raw);

// ── Step 2: Custom JSON Schema → TypeScript converter ─────────────────

/**
 * Resolve a JSON Schema type node to a TypeScript type string.
 * Handles: primitives, $ref, anyOf (nullable), arrays, objects.
 */
function resolveType(node, allSchemaNames) {
  if (!node) return "unknown";

  // $ref → top-level type name (strip "#/$defs/" prefix)
  if (node.$ref) {
    const refName = node.$ref.replace("#/$defs/", "");
    // Use the TS name if mapped, otherwise use as-is
    return name_map[refName] || refName;
  }

  // anyOf → typically Pydantic's nullable pattern: [{type/ref}, {type: "null"}]
  if (node.anyOf) {
    const nonNull = node.anyOf.filter((n) => n.type !== "null");
    const hasNull = node.anyOf.some((n) => n.type === "null");
    if (nonNull.length === 1) {
      const inner = resolveType(nonNull[0], allSchemaNames);
      return hasNull ? `${inner} | null` : inner;
    }
    // Multiple non-null types
    const parts = nonNull.map((n) => resolveType(n, allSchemaNames));
    if (hasNull) parts.push("null");
    return parts.join(" | ");
  }

  // enum → union literal
  if (node.enum) {
    return node.enum.map((v) => JSON.stringify(v)).join(" | ");
  }

  // array
  if (node.type === "array") {
    const itemType = resolveType(node.items, allSchemaNames);
    const needsParens = itemType.includes("|");
    return needsParens ? `(${itemType})[]` : `${itemType}[]`;
  }

  // object (untyped dict)
  if (node.type === "object" && !node.properties) {
    return "Record<string, unknown>";
  }

  // primitives
  switch (node.type) {
    case "string":
      return "string";
    case "integer":
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "null":
      return "null";
    default:
      return "unknown";
  }
}

/**
 * Convert an enum schema to a TS type alias.
 */
function emitEnum(name, schema) {
  const members = schema.enum.map((v) => JSON.stringify(v)).join(" | ");
  return `export type ${name} = ${members};\n`;
}

/**
 * Convert an object schema to a TS interface.
 */
function emitInterface(name, schema, allSchemaNames) {
  const required = new Set(schema.required || []);
  const lines = [`export interface ${name} {`];

  for (const [field, prop] of Object.entries(schema.properties || {})) {
    const tsType = resolveType(prop, allSchemaNames);
    const optional = !required.has(field);
    lines.push(`  ${field}${optional ? "?" : ""}: ${tsType};`);
  }

  lines.push("}");
  return lines.join("\n") + "\n";
}

// ── Step 3: Generate TypeScript ───────────────────────────────────────

function main() {
  const allSchemaNames = new Set(Object.keys(schemas));
  console.log(`[generate-types] Converting ${allSchemaNames.size} schemas...`);

  let output = `// AUTO-GENERATED — DO NOT EDIT MANUALLY\n`;
  output += `// Source: Pydantic models in CHATVOTE-BackEnd/src/models/\n`;
  output += `// Generated by: scripts/generate-types.mjs\n`;
  output += `// Re-run: pnpm run generate:types\n`;

  let count = 0;
  for (const [pyName, schema] of Object.entries(schemas)) {
    const tsName = name_map[pyName] || pyName;
    output += `\n// --- ${tsName} ---\n`;

    if (schema.enum) {
      output += emitEnum(tsName, schema);
    } else if (schema.type === "object" && schema.properties) {
      output += emitInterface(tsName, schema, allSchemaNames);
    } else {
      console.warn(`[generate-types] Skipping unknown schema shape: ${pyName}`);
      continue;
    }
    count++;
  }

  // Socket.IO event maps
  output += `\n// ============================================\n`;
  output += `// Socket.IO Event Maps\n`;
  output += `// ============================================\n\n`;

  output += `export interface ServerToClientEvents {\n`;
  for (const [event, dtoName] of Object.entries(
    socket_events.server_to_client,
  )) {
    const tsName = name_map[dtoName] || dtoName;
    output += `  ${event}: (data: ${tsName}) => void;\n`;
  }
  output += `}\n\n`;

  output += `export interface ClientToServerEvents {\n`;
  for (const [event, dtoName] of Object.entries(
    socket_events.client_to_server,
  )) {
    const tsName = name_map[dtoName] || dtoName;
    output += `  ${event}: (data: ${tsName}) => void;\n`;
  }
  output += `}\n`;

  // Write
  mkdirSync(OUTPUT_DIR, { recursive: true });
  writeFileSync(OUTPUT_FILE, output, "utf-8");
  console.log(`[generate-types] Written to ${OUTPUT_FILE}`);
  console.log(`[generate-types] Generated ${count} types + event maps`);
}

main();
