#!/usr/bin/env bash
# ragflow-init.sh — Auto-register admin account and generate API key in RAGFlow.
#
# Called by `make seed-ragflow`. Waits for RAGFlow to be healthy,
# registers the dev account, and writes the API key to .env.local.
#
# This avoids manual UI setup for local development.

set -euo pipefail

RAGFLOW_URL="${RAGFLOW_API_URL:-http://localhost:9380}"
RAGFLOW_WEB="${RAGFLOW_URL/9380/8680}"
EMAIL="${RAGFLOW_ADMIN_EMAIL:-admin@chatvote.local}"
PASSWORD="${RAGFLOW_ADMIN_PASSWORD:-chatvote123}"
NICKNAME="${RAGFLOW_ADMIN_NICKNAME:-ChatVote Admin}"
ENV_FILE="${1:-CHATVOTE-FrontEnd/.env.local}"

echo "═══ RAGFlow Init ═══"
echo "  API URL:  $RAGFLOW_URL"
echo "  Email:    $EMAIL"
echo "  Env file: $ENV_FILE"

# 1. Wait for RAGFlow to be ready
echo ""
echo "→ Waiting for RAGFlow..."
for i in $(seq 1 30); do
  if curl -sf "$RAGFLOW_WEB/" > /dev/null 2>&1; then
    echo "  ✓ RAGFlow is ready"
    break
  fi
  if [ "$i" -eq 30 ]; then
    echo "  ✗ RAGFlow not ready after 30 attempts"
    echo "  Start it with: docker compose -f docker-compose.dev.yml --profile ragflow up -d"
    exit 1
  fi
  sleep 2
done

# 2. Register admin account (idempotent — returns error if exists, that's fine)
echo ""
echo "→ Registering admin account..."
REG_RESPONSE=$(curl -sf -X POST "$RAGFLOW_URL/api/v1/user/register" \
  -H "Content-Type: application/json" \
  -d "{\"email\":\"$EMAIL\",\"password\":\"$PASSWORD\",\"nickname\":\"$NICKNAME\"}" 2>/dev/null || echo '{"code":-1}')

REG_CODE=$(echo "$REG_RESPONSE" | python3 -c "import sys,json; print(json.load(sys.stdin).get('code','-1'))" 2>/dev/null || echo "-1")

if [ "$REG_CODE" = "0" ]; then
  echo "  ✓ Account created"
elif echo "$REG_RESPONSE" | grep -qi "exist\|duplicate\|already"; then
  echo "  ✓ Account already exists"
else
  echo "  ⚠ Registration response: $REG_RESPONSE"
  echo "  (Continuing — account may already exist)"
fi

# 3. Login to get session token
echo ""
echo "→ Logging in..."
LOGIN_RESPONSE=$(curl -sf -X POST "$RAGFLOW_URL/api/v1/user/login" \
  -H "Content-Type: application/json" \
  -d "{\"email\":\"$EMAIL\",\"password\":\"$PASSWORD\"}" \
  -c /tmp/ragflow-cookies.txt 2>/dev/null || echo '{"code":-1}')

# Try to extract token from response or cookie
SESSION=$(cat /tmp/ragflow-cookies.txt 2>/dev/null | grep -i 'session\|token' | awk '{print $NF}' | head -1 || echo "")

if [ -z "$SESSION" ]; then
  # RAGFlow v0.24 may use different login endpoint
  LOGIN_RESPONSE=$(curl -sf -X POST "$RAGFLOW_URL/v1/user/login" \
    -H "Content-Type: application/json" \
    -d "{\"email\":\"$EMAIL\",\"password\":\"$PASSWORD\"}" \
    -c /tmp/ragflow-cookies.txt 2>/dev/null || echo '{"code":-1}')
  SESSION=$(cat /tmp/ragflow-cookies.txt 2>/dev/null | grep -i 'session\|token' | awk '{print $NF}' | head -1 || echo "")
fi

if [ -z "$SESSION" ]; then
  echo "  ⚠ Could not auto-login via API."
  echo ""
  echo "  Manual steps needed:"
  echo "    1. Open $RAGFLOW_WEB"
  echo "    2. Login with $EMAIL / $PASSWORD"
  echo "    3. Click avatar → API Keys → Create"
  echo "    4. Add to $ENV_FILE:"
  echo "       RAGFLOW_API_KEY=ragflow-xxxx"
  echo ""

  # Check if key already exists in env file
  if grep -q "RAGFLOW_API_KEY" "$ENV_FILE" 2>/dev/null; then
    EXISTING_KEY=$(grep "RAGFLOW_API_KEY" "$ENV_FILE" | head -1 | cut -d= -f2)
    if [ -n "$EXISTING_KEY" ] && [ "$EXISTING_KEY" != "" ]; then
      echo "  ✓ RAGFLOW_API_KEY already set in $ENV_FILE — using it"
      exit 0
    fi
  fi
  exit 0
fi

echo "  ✓ Logged in"

# 4. Generate API key
echo ""
echo "→ Generating API key..."
API_KEY_RESPONSE=$(curl -sf -X POST "$RAGFLOW_URL/api/v1/system/new_token" \
  -H "Authorization: Bearer $SESSION" \
  -H "Content-Type: application/json" \
  -b /tmp/ragflow-cookies.txt 2>/dev/null || \
  curl -sf -X POST "$RAGFLOW_URL/v1/system/new_token" \
  -b /tmp/ragflow-cookies.txt 2>/dev/null || echo '{"code":-1}')

API_KEY=$(echo "$API_KEY_RESPONSE" | python3 -c "
import sys, json
d = json.load(sys.stdin)
# Try different response shapes
print(d.get('data', {}).get('token', '') or d.get('data', '') or '')
" 2>/dev/null || echo "")

if [ -n "$API_KEY" ] && [ "$API_KEY" != "" ]; then
  echo "  ✓ API key generated: ${API_KEY:0:12}..."

  # 5. Write to .env.local
  if grep -q "^RAGFLOW_API_KEY=" "$ENV_FILE" 2>/dev/null; then
    sed -i.bak "s|^RAGFLOW_API_KEY=.*|RAGFLOW_API_KEY=$API_KEY|" "$ENV_FILE"
    rm -f "$ENV_FILE.bak"
    echo "  ✓ Updated RAGFLOW_API_KEY in $ENV_FILE"
  else
    echo "" >> "$ENV_FILE"
    echo "# RAGFlow API key (auto-generated by scripts/ragflow-init.sh)" >> "$ENV_FILE"
    echo "RAGFLOW_API_KEY=$API_KEY" >> "$ENV_FILE"
    echo "  ✓ Added RAGFLOW_API_KEY to $ENV_FILE"
  fi
else
  echo "  ⚠ Could not auto-generate API key."
  echo "    Generate manually: RAGFlow UI → avatar → API Keys → Create"
  echo "    Then add to $ENV_FILE: RAGFLOW_API_KEY=<key>"
fi

rm -f /tmp/ragflow-cookies.txt
echo ""
echo "═══ Done ═══"
